// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

jest.setTimeout(30000);

describe('disponibilidad', function() {
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    if (driver) { await driver.quit(); }
  })
  it('disponibilidad', async function() {
    await driver.get("https://10.6.131.134/")
    await driver.manage().window().setRect({ width: 1854, height: 1048 })
    await driver.findElement(By.css(".w-full:nth-child(1)")).click()
    await driver.findElement(By.css(".w-full:nth-child(1)")).sendKeys("fisio1@ull.es")
    await driver.findElement(By.css(".w-full:nth-child(2)")).click()
    await driver.findElement(By.css(".w-full:nth-child(2)")).sendKeys("123456")
    await driver.findElement(By.css(".bg-teal-600")).click()
    await driver.findElement(By.linkText("Disponibilidad")).click()
    await driver.findElement(By.css(".border:nth-child(1) .text-sm")).click()
    await driver.findElement(By.css(".ml-auto")).click()
    await driver.findElement(By.css(".border:nth-child(1) .text-sm")).click()
    await driver.findElement(By.css(".px-4")).click()
    await driver.findElement(By.css(".px-4")).click()
    await driver.findElement(By.css(".px-4")).click()
    await driver.findElement(By.css(".w-full")).click()
  })
})