// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

jest.setTimeout(30000);

describe('VerPanelInformacionFisio', function() {
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    if (driver) { await driver.quit(); }
  })
  it('VerPanelInformacionFisio', async function() {
    await driver.get("https://10.6.131.134/")
    await driver.manage().window().setRect({ width: 979, height: 1063 })
    await driver.findElement(By.css(".w-full:nth-child(1)")).click()
    await driver.findElement(By.css(".w-full:nth-child(1)")).sendKeys("fisio1@ull.es")
    await driver.findElement(By.css(".w-full:nth-child(2)")).click()
    await driver.findElement(By.css(".w-full:nth-child(2)")).sendKeys("123456")
    await driver.findElement(By.css(".bg-teal-600")).click()
    await driver.findElement(By.linkText("Panel de Información")).click()
    await driver.findElement(By.css(".bg-white:nth-child(1) .flex > .text-sm")).click()
    await driver.findElement(By.css(".bg-white:nth-child(1) .flex > .text-sm")).click()
    await driver.findElement(By.css(".bg-white:nth-child(2) .flex > .text-sm")).click()
    await driver.findElement(By.css(".bg-white:nth-child(2) .flex > .text-sm")).click()
    await driver.findElement(By.css(".bg-white:nth-child(4) .flex > .text-sm")).click()
    await driver.findElement(By.css(".bg-white:nth-child(4) .flex > .text-sm")).click()
    await driver.findElement(By.css(".p-2:nth-child(1) .font-bold")).click()
    await driver.findElement(By.css(".py-1:nth-child(2)")).click()
    await driver.findElement(By.css(".rounded-md:nth-child(1)")).click()
    await driver.findElement(By.css(".w-full")).click()
  })
})