// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

jest.setTimeout(30000);

describe('VerPerfilCliente', function() {
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    if (driver) { await driver.quit(); }
  })
  it('VerPerfilCliente', async function() {
    await driver.get("https://10.6.131.134/")
    await driver.manage().window().setRect({ width: 1854, height: 1048 })
    await driver.findElement(By.css(".w-full:nth-child(1)")).click()
    await driver.findElement(By.css(".w-full:nth-child(1)")).sendKeys("nano@ull.es")
    await driver.findElement(By.css(".w-full:nth-child(2)")).click()
    await driver.findElement(By.css(".w-full:nth-child(2)")).sendKeys("123456")
    await driver.findElement(By.css(".bg-teal-600")).click()
    await driver.findElement(By.linkText("Ver mi perfil")).click()
    await driver.findElement(By.css(".mt-6:nth-child(7)")).click()
    await driver.findElement(By.css(".text-gray-600")).click()
    await driver.findElement(By.css(".mt-6:nth-child(8)")).click()
    await driver.findElement(By.css(".mt-6:nth-child(8)")).click()
    {
      const element = await driver.findElement(By.css(".flex-1:nth-child(3)"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    {
      const element = await driver.findElement(By.css(".flex-1:nth-child(3)"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.css(".flex-1:nth-child(3)"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    await driver.findElement(By.css(".flex-1:nth-child(3)")).click()
  })
})