// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')
const firefox = require('selenium-webdriver/firefox')

describe('GestionUsuarios', function() {
  jest.setTimeout(60000)
  let driver
  let vars
  beforeEach(async function() {
    const options = new firefox.Options()
    options.setBinary('/usr/bin/firefox-esr')
    options.addArguments('--headless')
    options.addArguments('--no-sandbox')
    options.addArguments('--disable-dev-shm-usage')
    options.addArguments('--window-size=1920,1080')
    options.setAcceptInsecureCerts(true)
    driver = await new Builder().forBrowser('firefox').setFirefoxOptions(options).build()
    vars = {}
  })
  afterEach(async function() {
    if (driver) await driver.quit();
  })
  it('GestionUsuarios', async function() {
    await driver.get("https://10.6.131.134/")
    await driver.manage().window().setRect({ width: 1854, height: 1048 })
    await driver.findElement(By.css(".w-full:nth-child(1)")).click()
    await driver.findElement(By.css(".w-full:nth-child(1)")).sendKeys("admin1@ull.es")
    await driver.findElement(By.css(".w-full:nth-child(2)")).click()
    await driver.findElement(By.css(".w-full:nth-child(2)")).sendKeys("123456")
    await driver.findElement(By.css(".bg-teal-600")).click()
    await driver.findElement(By.css(".flex:nth-child(2) > span")).click()
    await driver.findElement(By.css(".appearance-none")).click()
    {
      const dropdown = await driver.findElement(By.css(".appearance-none"))
      await dropdown.findElement(By.xpath("//option[. = 'Clientes']")).click()
    }
    await driver.findElement(By.css(".rounded-xl > option:nth-child(2)")).click()
    await driver.findElement(By.css(".appearance-none")).click()
    {
      const dropdown = await driver.findElement(By.css(".appearance-none"))
      await dropdown.findElement(By.xpath("//option[. = 'Fisioterapeutas']")).click()
    }
    await driver.findElement(By.css(".rounded-xl > option:nth-child(3)")).click()
    await driver.findElement(By.css(".appearance-none")).click()
    {
      const dropdown = await driver.findElement(By.css(".appearance-none"))
      await dropdown.findElement(By.xpath("//option[. = 'Administradores']")).click()
    }
    await driver.findElement(By.css("option:nth-child(4)")).click()
    await driver.findElement(By.css(".appearance-none")).click()
    {
      const dropdown = await driver.findElement(By.css(".appearance-none"))
      await dropdown.findElement(By.xpath("//option[. = 'Todos los roles']")).click()
    }
    await driver.findElement(By.css(".rounded-xl > option:nth-child(1)")).click()
    await driver.findElement(By.css(".px-4")).click()
    await driver.findElement(By.css(".hover\\3A bg-teal-50\\/50:nth-child(2) .bg-sky-500\\/10 > .lucide")).click()
    await driver.findElement(By.css(".px-5:nth-child(1)")).click()
  })
})