// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')
const firefox = require('selenium-webdriver/firefox')

describe('Ausencias', function() {
  jest.setTimeout(60000)
  let driver
  let vars
  beforeEach(async function() {
    const options = new firefox.Options()
    options.setBinary('/usr/bin/firefox-esr')
    options.addArguments('--headless')
    options.addArguments('--no-sandbox')
    options.addArguments('--disable-dev-shm-usage')
    options.addArguments('--window-size=1920,1080')
    options.setAcceptInsecureCerts(true)
    driver = await new Builder().forBrowser('firefox').setFirefoxOptions(options).build()
    vars = {}
  })
  afterEach(async function() {
    if (driver) await driver.quit();
  })
  it('Ausencias', async function() {
    await driver.get("https://10.6.131.134/")
    await driver.manage().window().setRect({ width: 1854, height: 1048 })
    await driver.findElement(By.css(".w-full:nth-child(1)")).click()
    await driver.findElement(By.css(".w-full:nth-child(1)")).sendKeys("fisio1@ull.es")
    await driver.findElement(By.css(".w-full:nth-child(2)")).click()
    await driver.findElement(By.css(".w-full:nth-child(2)")).sendKeys("123456")
    await driver.findElement(By.css(".bg-teal-600")).click()
    await driver.findElement(By.css(".flex:nth-child(3) > span")).click()
    await driver.findElement(By.css("div:nth-child(1) > .w-full")).click()
    await driver.findElement(By.css("div:nth-child(1) > .w-full")).sendKeys("2025-12-17")
    await driver.findElement(By.css(".bg-red-600")).click()
  })
})