// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')
const firefox = require('selenium-webdriver/firefox')

describe('PanelFisio', function() {
  jest.setTimeout(60000)
  let driver
  let vars
  beforeEach(async function() {
    const options = new firefox.Options()
    options.setBinary('/usr/bin/firefox-esr')
    options.addArguments('--headless')
    options.addArguments('--no-sandbox')
    options.addArguments('--disable-dev-shm-usage')
    options.addArguments('--window-size=1920,1080')
    options.setAcceptInsecureCerts(true)
    driver = await new Builder().forBrowser('firefox').setFirefoxOptions(options).build()
    vars = {}
  })
  afterEach(async function() {
    if (driver) await driver.quit();
  })
  it('PanelFisio', async function() {
    await driver.get("https://10.6.131.134/login")
    await driver.manage().window().setRect({ width: 1854, height: 1048 })
    await driver.findElement(By.css(".w-full:nth-child(1)")).click()
    await driver.findElement(By.css(".w-full:nth-child(1)")).sendKeys("fisio1@ull.es")
    await driver.findElement(By.css(".w-full:nth-child(2)")).click()
    await driver.findElement(By.css(".w-full:nth-child(2)")).sendKeys("123456")
    await driver.findElement(By.css(".bg-teal-600")).click()
    
    await driver.wait(until.elementLocated(By.css(".bg-gray-200:nth-child(2)")), 20000).click()
    
    await driver.findElement(By.css("section:nth-child(3) .px-4:nth-child(3)")).click()
    await driver.findElement(By.css("section:nth-child(3) .px-4:nth-child(1)")).click()
    await driver.findElement(By.css("section:nth-child(4) .px-4:nth-child(3)")).click()
    await driver.findElement(By.css(".bg-white:nth-child(1) .flex > .text-sm")).click()
    await driver.findElement(By.css(".bg-white:nth-child(1) .flex > .text-sm")).click()
    await driver.findElement(By.css("section:nth-child(4) .px-4:nth-child(2)")).click()
    
    const dropdownEstado = await driver.wait(until.elementLocated(By.css(".focus\\3Aring-teal-500:nth-child(1)")), 10000)
    await dropdownEstado.click()
    {
      const dropdown = await driver.findElement(By.css(".focus\\3Aring-teal-500:nth-child(1)"))
      await dropdown.findElement(By.xpath("//option[. = 'Pendientes']")).click()
    }
    
    await driver.findElement(By.css(".bg-white:nth-child(1) > option:nth-child(2)")).click()
    
    await driver.findElement(By.css(".focus\\3Aring-teal-500:nth-child(1)")).click()
    await driver.findElement(By.css(".focus\\3Aring-teal-500:nth-child(1)")).click()
    {
      const dropdown = await driver.findElement(By.css(".focus\\3Aring-teal-500:nth-child(1)"))
      await dropdown.findElement(By.xpath("//option[. = 'Estado: Todos']")).click()
    }
    await driver.findElement(By.css(".bg-white:nth-child(1) > option:nth-child(1)")).click()
    
    await driver.findElement(By.css(".focus\\3A border-teal-500:nth-child(2)")).click()
    {
      const dropdown = await driver.findElement(By.css(".focus\\3A border-teal-500:nth-child(2)"))
      await dropdown.findElement(By.xpath("//option[. = 'Octubre']")).click()
    }
    await driver.findElement(By.css("option:nth-child(11)")).click()
    
    await driver.findElement(By.css(".focus\\3A border-teal-500:nth-child(2)")).click()
    {
      const dropdown = await driver.findElement(By.css(".focus\\3A border-teal-500:nth-child(2)"))
      await dropdown.findElement(By.xpath("//option[. = 'Todos los meses']")).click()
    }
    await driver.findElement(By.css(".bg-white:nth-child(2) > option:nth-child(1)")).click()
    
    await driver.findElement(By.css(".border-gray-300:nth-child(3)")).click()
    {
      const dropdown = await driver.findElement(By.css(".border-gray-300:nth-child(3)"))
      await dropdown.findElement(By.xpath("//option[. = '2025']")).click()
    }
    await driver.findElement(By.css(".bg-white:nth-child(3) > option:nth-child(3)")).click()
    
    await driver.findElement(By.css(".border-gray-300:nth-child(3)")).click()
    {
      const dropdown = await driver.findElement(By.css(".border-gray-300:nth-child(3)"))
      await dropdown.findElement(By.xpath("//option[. = 'Todos los años']")).click()
    }
    await driver.findElement(By.css(".bg-white:nth-child(3) > option:nth-child(1)")).click()
  })
})