//server/t-e2e/scripts-js/cancelarCitaCliente.spec.js
// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')
const firefox = require('selenium-webdriver/firefox')

describe('CancelarCitaCliente', function() {
  jest.setTimeout(60000)
  let driver
  let vars
  
  beforeEach(async function() {
    const options = new firefox.Options()
    options.setBinary('/usr/bin/firefox-esr')
    options.addArguments('--headless')
    options.addArguments('--no-sandbox')
    options.addArguments('--disable-dev-shm-usage')
    options.setAcceptInsecureCerts(true)

    driver = await new Builder()
      .forBrowser('firefox')
      .setFirefoxOptions(options)
      .build()
    vars = {}
  })

  afterEach(async function() {
    if (driver) await driver.quit();
  })

  it('CancelarCitaCliente', async function() {
    await driver.get("https://10.6.131.134/")
    await driver.manage().window().setRect({ width: 1854, height: 1048 })
    
    // Login
    await driver.findElement(By.css(".w-full:nth-child(1)")).sendKeys("nano@ull.es")
    await driver.findElement(By.css(".w-full:nth-child(2)")).sendKeys("123456")
    await driver.findElement(By.css("button[type='submit']")).click()
    
    // Esperar a que cargue el dashboard
    await driver.sleep(5000)
    
    // Usar el enlace exacto
    await driver.findElement(By.linkText("Reservar cita")).click()
    
    await driver.sleep(3000)
    
    // Continuar con el resto del flujo original
    await driver.findElement(By.css(".border-gray-300")).click()
    {
      const dropdown = await driver.findElement(By.css(".border-gray-300"))
      await dropdown.findElement(By.xpath("//option[. = 'fisio1 uno']")).click()
    }
    await driver.findElement(By.css("option:nth-child(2)")).click()
    await driver.findElement(By.css(".hover\\3A bg-teal-600")).click()
    await driver.findElement(By.css(".text-indigo-700")).click()
    await driver.findElement(By.css(".bg-red-50")).click()
    await driver.findElement(By.css(".inline-flex:nth-child(1)")).click()
    await driver.findElement(By.css(".bg-red-600")).click()
  })
})