// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')
const firefox = require('selenium-webdriver/firefox')

describe('IncioSesion-verperfil', function() {
  this.timeout(30000)
  let driver
  let vars
  
  beforeEach(async function() {
    const options = new firefox.Options()
    options.setBinary('/usr/bin/firefox-esr')
    options.addArguments('--headless')
    options.addArguments('--no-sandbox')
    options.addArguments('--disable-dev-shm-usage')
    options.setAcceptInsecureCerts(true)

    driver = await new Builder()
      .forBrowser('firefox')
      .setFirefoxOptions(options)
      .build()
    vars = {}
  })

  afterEach(async function() {
    if (driver) await driver.quit();
  })

  it('IncioSesion-verperfil', async function() {
    await driver.get("https://10.6.131.134/")
    await driver.manage().window().setRect({ width: 1854, height: 1048 })
    await driver.findElement(By.css(".w-full:nth-child(1)")).click()
    await driver.findElement(By.css(".w-full:nth-child(1)")).sendKeys("nano@ull.es")
    await driver.findElement(By.css(".w-full:nth-child(2)")).click()
    await driver.findElement(By.css(".w-full:nth-child(2)")).sendKeys("123456")
    await driver.findElement(By.css(".bg-teal-600")).click()
    await driver.findElement(By.linkText("Ver mi perfil")).click()
    await driver.findElement(By.css(".mt-6:nth-child(7)")).click()
    await driver.findElement(By.css(".bg-teal-600")).click()
    
    // FIX: Manejar la alerta
    await driver.wait(until.alertIsPresent(), 5000)
    const alert = await driver.switchTo().alert()
    assert.strictEqual(await alert.getText(), "Perfil actualizado correctamente")
    await alert.accept()

    await driver.findElement(By.css(".mt-6:nth-child(8)")).click()
    await driver.findElement(By.css(".mt-6:nth-child(8)")).click()
    await driver.findElement(By.css(".w-full")).click()
  })
})
