// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')
const firefox = require('selenium-webdriver/firefox')

describe('IncioSesion-cita', function() {
  this.timeout(60000)
  let driver
  let vars
  
  beforeEach(async function() {
    const options = new firefox.Options()
    options.setBinary('/usr/bin/firefox-esr')
    options.addArguments('--headless')
    options.addArguments('--no-sandbox')
    options.addArguments('--disable-dev-shm-usage')
    options.setAcceptInsecureCerts(true)

    driver = await new Builder()
      .forBrowser('firefox')
      .setFirefoxOptions(options)
      .build()
    vars = {}
  })

  afterEach(async function() {
    if (driver) await driver.quit();
  })

  it('IncioSesion-cita', async function() {
    await driver.get("https://10.6.131.134/login")
    await driver.manage().window().setRect({ width: 1854, height: 1048 })
    
    // Login
    await driver.findElement(By.css(".w-full:nth-child(1)")).click()
    await driver.findElement(By.css(".w-full:nth-child(1)")).sendKeys("nano@ull.es")
    await driver.findElement(By.css(".w-full:nth-child(2)")).click()
    await driver.findElement(By.css(".w-full:nth-child(2)")).sendKeys("123456")
    await driver.findElement(By.css(".bg-teal-600")).click()
    
    // Ir a Citas
    await driver.findElement(By.linkText("Citas")).click()
    
    // Espera para carga inicial
    await driver.sleep(3000) 
    
    // Seleccionar Fisio
    await driver.findElement(By.css(".border-gray-300")).click()
    {
      const dropdown = await driver.findElement(By.css(".border-gray-300"))
      await dropdown.findElement(By.xpath("//option[. = 'fisio1 uno']")).click()
    }
    await driver.findElement(By.css("option:nth-child(2)")).click()
    
    await driver.sleep(2000) // Esperar a que cargue el calendario

    // --- LÓGICA DE "FUERZA BRUTA" INTELIGENTE ---
    // Vamos a buscar todas las celdas del calendario e intentar clickar una por una
    // hasta que el modal se abra.
    console.log("DEBUG: Buscando un día disponible...");
    
    // Asumimos que las celdas son los elementos con borde dentro del contenedor principal
    // Empezamos desde el indice 10 para saltarnos los headers o días vacíos del mes anterior
    let modalAbierto = false;
    
    // Obtenemos todas las posibles celdas
    // (Usamos un selector genérico que suele coincidir con las celdas del calendario)
    const celdas = await driver.findElements(By.css(".contents > .border"));
    
    // Probamos clickar desde la celda 10 hasta la 25 (para asegurar que caemos en mitad del mes)
    for (let i = 10; i < Math.min(celdas.length, 30); i++) {
        try {
            // Intentamos clickar la celda 'i'
            await driver.executeScript("arguments[0].click();", celdas[i]);
            
            // Esperamos medio segundo a ver si reacciona
            await driver.sleep(500); 
            
            // Verificamos SI EL INPUT APARECIÓ (esto significa éxito)
            const inputs = await driver.findElements(By.css("input[type='text']"));
            
            // Chequeamos si hay algún input visible
            for(let inp of inputs) {
                if(await inp.isDisplayed()) {
                    modalAbierto = true;
                    console.log(`DEBUG: ¡Éxito! Celda ${i} abrió el modal.`);
                    break;
                }
            }
            
            if (modalAbierto) break; // Salimos del bucle si funcionó
            
        } catch (err) {
            // Si falla el click en esa celda, seguimos a la siguiente sin llorar
        }
    }
    
    if (!modalAbierto) {
        throw new Error("No se pudo abrir el formulario de cita en ningún día probado.");
    }

    // -----------------------------------------------------

    // Ahora que sabemos que el modal está abierto, rellenamos
    const inputMotivo = await driver.findElement(By.css("input[type='text']"));
    await inputMotivo.sendKeys("Dolor selenium");

    // TextArea
    const textarea = await driver.wait(until.elementLocated(By.css("textarea")), 5000);
    await textarea.sendKeys("Prueba para selenium");

    // Enviar
    const btnEnviar = await driver.findElement(By.css(".bg-teal-600"));
    await driver.executeScript("arguments[0].click();", btnEnviar);
    
    await driver.sleep(2000)
    
    // Cerrar confirmación (si existe)
    try {
        const btnCerrar = await driver.findElement(By.css(".w-full"));
        if(await btnCerrar.isDisplayed()) {
             await btnCerrar.click();
        }
    } catch(e) {
        // Ignorar
    }
  })
})
