// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')
const firefox = require('selenium-webdriver/firefox')

describe('GetionCalendario', function() {
  jest.setTimeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    const options = new firefox.Options()
    options.setBinary('/usr/bin/firefox-esr')
    options.addArguments('--headless')
    options.addArguments('--no-sandbox')
    options.addArguments('--disable-dev-shm-usage')
    options.setAcceptInsecureCerts(true)
    driver = await new Builder().forBrowser('firefox').setFirefoxOptions(options).build()
    vars = {}
  })
  afterEach(async function() {
    if (driver) await driver.quit();
  })
  it('GetionCalendario', async function() {
    await driver.get("https://10.6.131.134/")
    await driver.manage().window().setRect({ width: 1226, height: 1063 })
    await driver.findElement(By.css(".w-full:nth-child(1)")).click()
    await driver.findElement(By.css(".w-full:nth-child(1)")).sendKeys("nano@ull.es")
    await driver.findElement(By.css(".w-full:nth-child(2)")).click()
    await driver.findElement(By.css(".w-full:nth-child(2)")).sendKeys("123456")
    await driver.findElement(By.css(".w-full:nth-child(2)")).sendKeys(Key.ENTER)
    await driver.sleep(3000)
    await driver.findElement(By.css(".gap-3:nth-child(3) > span")).click()
    await driver.findElement(By.css(".h-\\[120px\\]:nth-child(1) .text-left:nth-child(1)")).click()
    await driver.findElement(By.css(".px-4")).click()
    await driver.findElement(By.css(".h-\\[120px\\]:nth-child(3) > .text-xs")).click()
    await driver.findElement(By.css(".px-4")).click()
    await driver.findElement(By.css(".bg-emerald-500:nth-child(1)")).click()
    await driver.findElement(By.css(".border-gray-300")).click()
    await driver.findElement(By.css(".p-2:nth-child(3)")).click()
    await driver.findElement(By.css(".rounded-lg:nth-child(1)")).click()
    await driver.findElement(By.css(".rounded-lg:nth-child(1)")).click()
    await driver.findElement(By.css(".p-2:nth-child(3)")).click()
  })
})