// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')
const firefox = require('selenium-webdriver/firefox')

describe('ReservarCita', function() {
  jest.setTimeout(60000)
  let driver
  let vars
  beforeEach(async function() {
    const options = new firefox.Options()
    options.setBinary('/usr/bin/firefox-esr')
    options.addArguments('--headless')
    options.addArguments('--no-sandbox')
    options.addArguments('--disable-dev-shm-usage')
    options.addArguments('--window-size=1920,1080')
    options.addArguments('--start-maximized')
    options.setAcceptInsecureCerts(true)
    driver = await new Builder().forBrowser('firefox').setFirefoxOptions(options).build()
    vars = {}
  })
  afterEach(async function() {
    if (driver) await driver.quit();
  })
  it('ReservarCita', async function() {
    await driver.get("https://10.6.131.134/")
    await driver.manage().window().setRect({ width: 1920, height: 1080 })
    await driver.findElement(By.css(".w-full:nth-child(1)")).click()
    await driver.findElement(By.css(".w-full:nth-child(1)")).sendKeys("nano@ull.es")
    await driver.findElement(By.css(".w-full:nth-child(2)")).click()
    await driver.findElement(By.css(".w-full:nth-child(2)")).sendKeys("123456")
    await driver.findElement(By.css(".bg-teal-600")).click()
    
    await driver.wait(until.elementLocated(By.css(".gap-3:nth-child(2) > span")), 20000).click()
    await driver.wait(until.elementLocated(By.css(".pl-10")), 10000).click()
    
    await driver.findElement(By.css(".flex > .px-3:nth-child(2)")).click()
    {
      const dropdown = await driver.findElement(By.css(".flex > .px-3:nth-child(2)"))
      await dropdown.findElement(By.xpath("//option[. = 'Deportiva']")).click()
    }
    await driver.findElement(By.css(".px-3:nth-child(2) > option:nth-child(3)")).click()
    
    await driver.findElement(By.css(".border-gray-300:nth-child(3)")).click()
    {
      const dropdown = await driver.findElement(By.css(".border-gray-300:nth-child(3)"))
      await dropdown.findElement(By.xpath("//option[contains(., '4+')]")).click()
    }
    await driver.findElement(By.css(".px-3:nth-child(3) > option:nth-child(3)")).click()
    
    await driver.findElement(By.css(".border-gray-300:nth-child(3)")).click()
    {
      const dropdown = await driver.findElement(By.css(".border-gray-300:nth-child(3)"))
      await dropdown.findElement(By.xpath("//option[contains(., 'Cualquier')]")).click()
    }
    await driver.findElement(By.css(".px-3:nth-child(3) > option:nth-child(1)")).click()

    await driver.sleep(5000) 
    
    const primerResultado = await driver.wait(
        until.elementLocated(By.xpath("(//div[contains(@class, 'grid')]//div[contains(@class, 'border')])[1]")), 
        20000
    )
    
    await driver.executeScript("arguments[0].scrollIntoView(true);", primerResultado)
    await driver.sleep(1000)
    await driver.executeScript("arguments[0].click();", primerResultado)

    const inputMotivo = await driver.wait(until.elementLocated(By.xpath("//input[@type='text' or not(@type)]")), 15000)
    await inputMotivo.click()
    await inputMotivo.sendKeys("Dolor lumbar")
    
    await driver.sleep(1000)
    
    const botonFinal = await driver.wait(until.elementLocated(By.xpath("//button[contains(@class, 'bg-teal-600')]")), 10000)
    await driver.executeScript("arguments[0].click();", botonFinal)
  })
})