// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')
const firefox = require('selenium-webdriver/firefox')

describe('Valoracion', function() {
  jest.setTimeout(60000)
  let driver
  let vars
  beforeEach(async function() {
    const options = new firefox.Options()
    options.setBinary('/usr/bin/firefox-esr')
    options.addArguments('--headless')
    options.addArguments('--no-sandbox')
    options.addArguments('--disable-dev-shm-usage')
    options.addArguments('--window-size=1920,1080')
    options.addArguments('--start-maximized')
    options.setAcceptInsecureCerts(true)
    driver = await new Builder().forBrowser('firefox').setFirefoxOptions(options).build()
    vars = {}
  })
  afterEach(async function() {
    if (driver) await driver.quit();
  })
  it('Valoracion', async function() {
    await driver.get("https://10.6.131.134/")
    await driver.manage().window().setRect({ width: 1920, height: 1080 })
    
    // --- LOGIN INICIAL ---
    await driver.findElement(By.css(".w-full:nth-child(1)")).click()
    await driver.findElement(By.css(".w-full:nth-child(1)")).sendKeys("nano@ull.es")
    await driver.findElement(By.css(".w-full:nth-child(2)")).click()
    await driver.findElement(By.css(".w-full:nth-child(2)")).sendKeys("123456")
    await driver.findElement(By.css(".w-full:nth-child(2)")).sendKeys(Key.ENTER)
    
    // IR A CALENDARIO
    await driver.wait(until.elementLocated(By.linkText("Calendario")), 20000).click()
    
    // SELECCIONAR CITA Y VALORAR
    await driver.findElement(By.css(".h-\\[120px\\]:nth-child(3) .text-left:nth-child(2)")).click()
    await driver.findElement(By.css(".bg-amber-400")).click()
    
    await driver.findElement(By.css(".focus\\3Aoutline-none:nth-child(3) path")).click()
    await driver.findElement(By.css(".focus\\3Aoutline-none:nth-child(4) > .lucide")).click()
    await driver.findElement(By.css(".border")).click()
    await driver.findElement(By.css(".border")).sendKeys("Buen servicio")
    
    await driver.actions().sendKeys(Key.ENTER).perform()
    await driver.sleep(1000)
    
    // --- RECARGA FORZOSA ---
    await driver.get("https://10.6.131.134/")
    await driver.wait(until.elementLocated(By.css("body")), 15000)
    await driver.sleep(2000)
    
    // --- RE-LOGIN DE SEGURIDAD ---
    // Si al recargar nos echó al login, nos volvemos a loguear.
    // Buscamos si existe el campo de email.
    const camposLogin = await driver.findElements(By.css(".w-full:nth-child(1)"))
    if (camposLogin.length > 0) {
        try {
            // Intentamos escribir. Si es el dashboard, esto fallará o no hará nada, por eso el try/catch
            await camposLogin[0].sendKeys("nano@ull.es")
            await driver.findElement(By.css(".w-full:nth-child(2)")).sendKeys("123456")
            await driver.findElement(By.css(".w-full:nth-child(2)")).sendKeys(Key.ENTER)
            await driver.sleep(2000)
        } catch (e) {
            // Si falla, asumimos que ya estábamos dentro
        }
    }
    
    // CONTINUAR TEST
    const calLink = await driver.wait(until.elementLocated(By.linkText("Calendario")), 20000)
    await driver.executeScript("arguments[0].click();", calLink)
    
    await driver.sleep(2000)
    
    const itemLista = await driver.wait(until.elementLocated(By.xpath("(//div[contains(@class, 'border')])[1]")), 20000)
    await driver.executeScript("arguments[0].scrollIntoView(true);", itemLista)
    await driver.sleep(500)
    await driver.executeScript("arguments[0].click();", itemLista)
    
    try {
        const carousel = await driver.wait(until.elementLocated(By.css("[id^='carousel-']")), 5000)
        await carousel.click()
    } catch (e) {
    }
    
    await driver.sleep(1000)
    
    const botonesAbsolutos = await driver.findElements(By.xpath("//div[contains(@class, 'absolute')]"))
    if (botonesAbsolutos.length > 2) {
         await driver.executeScript("arguments[0].click();", botonesAbsolutos[botonesAbsolutos.length - 1])
    }
  })
})